# Generated by Django 5.0.4 on 2024-06-22 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Legislator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                (
                    "political_party",
                    models.CharField(
                        choices=[
                            ("D", "Democratic"),
                            ("R", "Republican"),
                            ("L", "Libertarian"),
                            ("G", "Green"),
                            ("C", "Constitution"),
                            ("Re", "Reform"),
                            ("S", "Socialist"),
                            ("LU", "Liberty Union"),
                            ("P", "Progessive"),
                            ("AI", "American Independent"),
                            ("KN", "Know Nothing"),
                            ("FS", "Free Soil"),
                            ("Po", "Populist"),
                            ("PL", "Progressive Labor"),
                            ("IA", "Independent American"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AL", "Alabama"),
                            ("AK", "Alaska"),
                            ("AZ", "Arizona"),
                            ("AR", "Arkansas"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("HI", "Hawaii"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("IA", "Iowa"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("ME", "Maine"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi"),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska"),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VT", "Vermont"),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia"),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                        ],
                        max_length=2,
                    ),
                ),
                ("district", models.SmallIntegerField()),
                ("congress_house", models.SmallIntegerField(choices=[(1, "Representative"), (2, "Senator")])),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(max_length=8)),
                ("title", models.CharField(max_length=250)),
                ("origin", models.CharField(choices=[("H.R.", "House Resolution"), ("S.", "Senator")], max_length=4)),
                ("slug", models.SlugField()),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="congress.legislator"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "bill",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="congress.bill"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoteResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vote_type", models.IntegerField(choices=[(1, "Supportes"), (2, "Opposes")])),
                (
                    "legislator",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="congress.legislator"
                    ),
                ),
                (
                    "vote",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="congress.vote"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vote",
            name="legislators",
            field=models.ManyToManyField(blank=True, through="congress.VoteResult", to="congress.legislator"),
        ),
        migrations.AddField(
            model_name="legislator",
            name="votes",
            field=models.ManyToManyField(blank=True, through="congress.VoteResult", to="congress.vote"),
        ),
    ]
