# Generated by Django 5.0.4 on 2024-05-05 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("congress", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="sponsor",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="congress.legislator"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="bill",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="congress.bill"
            ),
        ),
        migrations.AlterField(
            model_name="voteresult",
            name="legislator",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="congress.legislator"
            ),
        ),
        migrations.AlterField(
            model_name="voteresult",
            name="vote",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="congress.vote"
            ),
        ),
    ]
