# Generated by Django 5.0.4 on 2024-05-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("congress", "0002_alter_bill_sponsor_alter_vote_bill_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="number",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="origin",
            field=models.CharField(
                blank=True, choices=[("H.R.", "House Resolution"), ("S.", "Senator")], max_length=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legislator",
            name="congress_house",
            field=models.SmallIntegerField(blank=True, choices=[(1, "Representative"), (2, "Senator")], null=True),
        ),
        migrations.AddField(
            model_name="legislator",
            name="district",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legislator",
            name="political_party",
            field=models.CharField(
                blank=True,
                choices=[
                    ("D", "Democratic"),
                    ("R", "Republican"),
                    ("L", "Libertarian"),
                    ("G", "Green"),
                    ("C", "Constitution"),
                    ("Re", "Reform"),
                    ("S", "Socialist"),
                    ("LU", "Liberty Union"),
                    ("P", "Progessive"),
                    ("AI", "American Independent"),
                    ("KN", "Know Nothing"),
                    ("FS", "Free Soil"),
                    ("Po", "Populist"),
                    ("PL", "Progressive Labor"),
                    ("IA", "Independent American"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="legislator",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legislator",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AL", "Alabama"),
                    ("AK", "Alaska"),
                    ("AZ", "Arizona"),
                    ("AR", "Arkansas"),
                    ("CA", "California"),
                    ("CO", "Colorado"),
                    ("CT", "Connecticut"),
                    ("DE", "Delaware"),
                    ("FL", "Florida"),
                    ("GA", "Georgia"),
                    ("HI", "Hawaii"),
                    ("ID", "Idaho"),
                    ("IL", "Illinois"),
                    ("IN", "Indiana"),
                    ("IA", "Iowa"),
                    ("KS", "Kansas"),
                    ("KY", "Kentucky"),
                    ("LA", "Louisiana"),
                    ("ME", "Maine"),
                    ("MD", "Maryland"),
                    ("MA", "Massachusetts"),
                    ("MI", "Michigan"),
                    ("MN", "Minnesota"),
                    ("MS", "Mississippi"),
                    ("MO", "Missouri"),
                    ("MT", "Montana"),
                    ("NE", "Nebraska"),
                    ("NV", "Nevada"),
                    ("NH", "New Hampshire"),
                    ("NJ", "New Jersey"),
                    ("NM", "New Mexico"),
                    ("NY", "New York"),
                    ("NC", "North Carolina"),
                    ("ND", "North Dakota"),
                    ("OH", "Ohio"),
                    ("OK", "Oklahoma"),
                    ("OR", "Oregon"),
                    ("PA", "Pennsylvania"),
                    ("RI", "Rhode Island"),
                    ("SC", "South Carolina"),
                    ("SD", "South Dakota"),
                    ("TN", "Tennessee"),
                    ("TX", "Texas"),
                    ("UT", "Utah"),
                    ("VT", "Vermont"),
                    ("VA", "Virginia"),
                    ("WA", "Washington"),
                    ("WV", "West Virginia"),
                    ("WI", "Wisconsin"),
                    ("WY", "Wyoming"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
